### ISSUE TITLE
src.config and src.HINT missing

### ISSUE THREAD

**Issue by siardkuipers** [ChrisChen1023/HINT#1]
Hi Chris Chen,

Thank you for your interesting work. I'm looking forward to testing it on my own dataset. However, I think some of the code is missing. Could you please update it?

**Comment by ChrisChen1023** [comment]
Hi siardkuipers,

Thanks for your interests. We update the code. Cheers.

**Comment by xuehuapi** [comment]
> Hi Chris Chen,
> 
> Looking forward to you updating the relevant code.
