### ISSUE TITLE
test a celebhq

### ISSUE THREAD

**Issue by saeedhaghshenas1402** [ChrisChen1023/HINT#11]
Hi dear friend
I want to use your HINT project to test an image of celeba. I followed the github steps, but what folder should I put the test image in? And what should I do after that? I would be grateful if you could guide me.

**Comment by ChrisChen1023** [comment]
> Hi dear friend I want to use your HINT project to test an image of celeba. I followed the github steps, but what folder should I put the test image in? And what should I do after that? I would be grateful if you could guide me.

Hi there,

It does not matter where you put the test image, just use the generate the .flist file, basically it is a list for the paths of all testing images/masks. Please use the flist.py to generate the .flist file, and complete your config.yml by changing the path of 'TEST_INPAINT_IMAGE_FLIST' and 'TEST_MASK_FLIST'. That should be working.
