### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by SHIJILIANG01** [ChrisChen1023/HINT#14]
Thank you for your excellent work. The paper mentions inference time per image, can you provide the code for reference, thanks!

**Comment by ChrisChen1023** [comment]
Hi,

I show the code below. You need to import time at the beginning. 

                    tsince = int(round(time.time()*1000))
                    outputs_img = self.inpaint_model(images, masks)
                    ttime_elapsed = int(round(time.time()*1000))-tsince
                    print('test time elaspsed {}ms'.format(ttime_elapsed))



I also update in the ./src/HINT.py

Cheers.
