### ISSUE TITLE
Number of training iterations

### ISSUE THREAD

**Issue by mumingerlai** [ChrisChen1023/HINT#15]
Can I ask how many iterations of training you did? I noticed that your ablation experiment iterated 30,000 rounds and the results are different from the comparison experiment.

**Comment by mumingerlai** [comment]
> Hi,
> 
> The ablation study is trained for 30,000 iterations only. We fully trained our models for around two weeks on a single A100 GPU. Please follow our config and the performance should be same.

Thank you very much for your reply. I checked your configuration and it seems that you trained for 300,000 iterations. Is the number of iterations the same for each dataset?

**Comment by ChrisChen1023** [comment]
> > Hi,
> > The ablation study is trained for 30,000 iterations only. We fully trained our models for around two weeks on a single A100 GPU. Please follow our config and the performance should be same.
> 
> Thank you very much for your reply. I checked your configuration and it seems that you trained for 300,000 iterations. Is the number of iterations the same for each dataset?

That 300,000 iterations is just for default setting. Please change the number for different datasets, depends on the complexity of datasets.
