### ISSUE TITLE
about metrics

### ISSUE THREAD

**Issue by Marm7** [ChrisChen1023/HINT#16]
您好，我想请问一下，我是用敦煌预训练模型测试敦煌数据集时，得到的评价指标与论文中有些差距，可能是我的某些操作有问题

图一最后一行是我的复现结果
![image](https://github.com/ChrisChen1023/HINT/assets/73111468/079277c7-9aeb-4e49-a9d2-45a9421160d8)

同时，我也测试了MISF在敦煌数据集的指标（图二），同样与图一有很大差距
![image](https://github.com/ChrisChen1023/HINT/assets/73111468/bf4cd434-290c-4c76-a093-0a6cba9de591)

上述测试结果使用scikit-image==0.18.2，与MISF的版本相同

所以我想请问一下，是否我有没注意到的设置或操作导致结果产生了偏差
期待回复！Thanks！！

**Comment by ChrisChen1023** [comment]
Hi,

The issue happens to me before. But the reason could be different. You may wish to check the image size (after dataloder). Also, for dunhuang dataset, the mask threshold need to be 100, which is followed by MISF.

**Comment by Marm7** [comment]
感谢您的回复，我dataloder后的size均保持在256*256。将mask threshold设置为了100，得到的指标与论文中的更加接近，但也似乎仍在允许的误差之外
![image](https://github.com/ChrisChen1023/HINT/assets/73111468/b59405e2-87fb-4bb6-9b20-5ecbf451a7d1)

**Comment by ChrisChen1023** [comment]
Hi,

This issue does not happen to me. You could check are the images cropped before the dataloader. Others I guess it might be because of the environment setting.

**Comment by mmmjmmm** [comment]
> 感谢您的回复，我dataloder后的size均保持在256*256。将mask threshold设置为了100，得到的指标与论文中的更加接近，但也似乎仍在允许的误差之外 ![image](https://private-user-images.githubusercontent.com/73111468/340082326-b59405e2-87fb-4bb6-9b20-5ecbf451a7d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTA5OTUsIm5iZiI6MTczMTY1MDY5NSwicGF0aCI6Ii83MzExMTQ2OC8zNDAwODIzMjYtYjU5NDA1ZTItODdmYi00YmI2LTliMjAtNWVjYmY0NTFhN2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA2MDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNGEyZDk1YWY4NTAxMzNhMzRhNDExY2QxZjcyZmI5ZmFhY2FjODliODhlNDBiNmZhMmM5ODdiNGYwNWQyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.unLAWJTa4SIolsIA8XigiVtHSNWxetjVEJDmJIv32uA)

你好，请问你现在成功复现出论文的结果了吗？我的复现结果与你threshhold=100时相同。
