### ISSUE TITLE
Read the questions in the paper

### ISSUE THREAD

**Issue by zhangshilong2000** [ChrisChen1023/HINT#17]
Hello, I met a problem when reading your paper. In the Mask-aware Pixel-shuffle Down-sampling module, only the abstract formula PD() is given in the paper. Do you have a more detailed formula?

**Comment by ChrisChen1023** [comment]
Hi,

Thanks for your interest. We did not detail the PD in our paper since this is already detailed in the existing work 'Real-Time Single Image and Video Super-Resolution Using an Efficient Sub-Pixel Convolutional Neural Network'. Please feel free to gather useful information inside. Cheers.

**Comment by zhangshilong2000** [comment]
Thank you for your prompt reply, I wish you a happy life!
