### ISSUE TITLE
load model

### ISSUE THREAD

**Issue by xLuge** [ChrisChen1023/HINT#2]
when i load the model in './checkpoints/CelebA/InpaintingModel_gen.pth' , an error  'RuntimeError: Error(s) in loading state_dict for HINT:Unexpected key(s) in state_dict: "refinement.0.norm1_1.body.weight", "refinement.0.norm1_1.body.bias..."' occurs

**Comment by amssss0** [comment]
I had the same problem.

**Comment by ChrisChen1023** [comment]
> when i load the model in './checkpoints/CelebA/InpaintingModel_gen.pth' , an error 'RuntimeError: Error(s) in loading state_dict for HINT:Unexpected key(s) in state_dict: "refinement.0.norm1_1.body.weight", "refinement.0.norm1_1.body.bias..."' occurs

Hi Luge,

Thanks for your interests. To solve this you could use 'strict ＝False' during loading the model in 'model.py', which has been updated now. please let me know if you meet other problems. Cheers.

**Comment by ChrisChen1023** [comment]
> I had the same problem.

Please see the previous comment.
