### ISSUE TITLE
请问敦煌数据集的迭代次数设置为多少

### ISSUE THREAD

**Issue by CoisiniStar** [ChrisChen1023/HINT#20]
亲爱的开发者您好，我们非常非常认可您的工作。尽管我们的硬件设备不同，但我非常想尝试运行代码达到论文中类似的精度。但由于我是新手小白，在图像修复过程中没有经验，不知道如何设置迭代次数。所以在这里真挚的询问您，在敦煌数据集的训练过程中，您设置的迭代次数是多少，如果实在记不清，说一个大致的数也可以的，非常期待您的回复

**Comment by ChrisChen1023** [comment]
Hi,

Thanks for your interest. For the Dunhuang dataset, we train it for around 250k-300k iterations (con not remember it very clearly).

However, the iteration setting depends on the performance. We stop the training once we find it outperformed the SoTA methods. So the potential is probably worth further exploring.

**Comment by ChrisChen1023** [comment]
> 亲爱的开发者您好，我们非常非常认可您的工作。尽管我们的硬件设备不同，但我非常想尝试运行代码达到论文中类似的精度。但由于我是新手小白，在图像修复过程中没有经验，不知道如何设置迭代次数。所以在这里真挚的询问您，在敦煌数据集的训练过程中，您设置的迭代次数是多少，如果实在记不清，说一个大致的数也可以的，非常期待您的回复

Hi,

Thanks for your interest. For the Dunhuang dataset, we train it for around 250k-300k iterations (con not remember it very clearly).

However, the iteration setting depends on the performance. We stop the training once we find it outperformed the SoTA methods. So the potential is probably worth further exploring.

**Comment by CoisiniStar** [comment]
诚挚地感谢您的回复，您确实是一个优质的科研工作者，希望您能在科研的道路上越来越顺，最后献以诚挚的祝福！
