### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by zhangshilong2000** [ChrisChen1023/HINT#4]
您好，敦煌壁画的所使用的掩码数据集可以提供一下吗

**Comment by ChrisChen1023** [comment]
> 您好，敦煌壁画的所使用的掩码数据集可以提供一下吗

Hi Shilong,

We are happy to share the Dunhuang dataset. However given this this a cvpr workshop dataset and it is now close now. We are not sure is it a good way to publicly release the dataset by us. Here are two ways you could consider: 1. contact the Dunhuang dataset owner for the dataset. 2. provide us your name, email, institute, and purpose, so we are able to share it to you. Cheers.

**Comment by zhangshilong2000** [comment]
您好！
姓名：张世龙
***@***.***
机构：兰州交通大学
目的：我是一名研究生，正在研究基于深度学习的敦煌壁画修复，缺少相关的实验数据集，希望您能考虑一下可否分享数据集，我们不会用作其他途径，且不会进行传播。
&nbsp; &nbsp;感谢您的回复！


张世龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChrisChen1023/HINT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月13日(星期三) 晚上8:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChrisChen1023/HINT] 数据集 (Issue #4)





  
您好，敦煌壁画的所使用的掩码数据集可以提供一下吗
  
Hi Shilong,
 
We are happy to share the Dunhuang dataset. However given this this a cvpr workshop dataset and it is now close now. We are not sure is it a good way to publicly release the dataset by us. Here are two ways you could consider: 1. contact the Dunhuang dataset owner for the dataset. 2. provide us your name, email, institute, and purpose, so we are able to share it to you. Cheers.

**Comment by ChrisChen1023** [comment]
Hi Shilong,

Thanks for your information. The email address you provide seems to be blocked. Please contact me by email ***@***.***', I will share it with you by email. Also, I will delete your information in this issue to protect your privacy. Cheers.
________________________________

**Comment by zhangshilong2000** [comment]
***@***.***
感谢！


张世龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChrisChen1023/HINT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月13日(星期三) 晚上8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChrisChen1023/HINT] 数据集 (Issue #4)





 Hi Shilong, 
 
 Thanks for your information. The email address you provide seems to be blocked. Please contact me by email ***@***.***', I will share it with you by email. Also, I will delete your information in this issue to protect your privacy. Cheers. 
 ________________________________

**Comment by ChrisChen1023** [comment]
Hi,
My email address seems to be blocked as well. Please find the email address in my homepage on github, or you could find the email address in our paper.
________________________________
