### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by Rahaf-jaber** [ChrisChen1023/HINT#9]
Hi
I didn't know which file I should download if I want to train it using the CelebA-HQ dataset, and how the dataset folders should look to work well with code?

Thanks.

**Comment by ChrisChen1023** [comment]
> Hi I didn't know which file I should download if I want to train it using the CelebA-HQ dataset, and how the dataset folders should look to work well with code?
> 
> Thanks.

Hi,

For training on CelebA-HQ, you need to download the officially publiced CelebA-HQ dataset. Then, use the /script/flist.py file to generate the .flst file and set the path of the .flist file in your config fiile. Finally, runthe train.py to train the model. Hope this is helpful.

Cheers.
